# Generated by Django 5.0.2 on 2025-11-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código (SKU)'),
        ),
    ]
