# Generated by Django 5.0.2 on 2025-11-05 18:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_product_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantidade mínima para alerta de estoque baixo', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Estoque Mínimo'),
        ),
    ]
