# Docker Compose para produção com Caddy como proxy reverso
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-stockbit_db}
      POSTGRES_USER: ${DB_USER:-stockbit_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stockbit-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-stockbit_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    expose:
      - "8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS},caddy
      - DATABASE_URL=postgresql://${DB_USER:-stockbit_user}:${DB_PASSWORD}@db:5432/${DB_NAME:-stockbit_db}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    env_file:
      - .env
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn inventory_api.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    networks:
      - stockbit-network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=${VITE_API_URL}
    expose:
      - "80"
    volumes:
      - static_files:/usr/share/nginx/html/static
      - media_files:/usr/share/nginx/html/media
    networks:
      - stockbit-network
    restart: unless-stopped
    depends_on:
      - backend

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    networks:
      - stockbit-network
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    environment:
      - CADDY_ADMIN=0.0.0.0:2019

networks:
  stockbit-network:
    driver: bridge

volumes:
  postgres_data:
  static_files:
  media_files:
  caddy_data:
  caddy_config:
  caddy_logs:

